id: "01_alcanos"
titulo: "Alcanos"
objetivos:
  - Reconocer estructuras y nomenclatura IUPAC básica.
  - Relacionar propiedades físicas con estructura.
  - Introducir reactividad general.
imagen: "../../assets/logos/utn.png"
tags: ["Estructura", "Propiedades"]